# Task 3 ( Team)

### Team: (20 pts)
- Create a team notebook to read in the COVID-19 data (cases, deaths, and population) using pandas and display the dataframe in a notebook.
- Merge all the three variables (cases, deaths, and population) to create a super COVID-19 datafame. Export it to a csv format.

Importing pandas library to read and merge csv files

In [1]:
import pandas as pd

Reading cases csv file and displaying the cases dataframe

In [2]:
covid_cases = pd.read_csv("../../../data/Stage_1/covid_confirmed_usafacts.csv")
covid_cases

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,19205,19205,19205,19205,19205,19318,19318,19318,19318,19318
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,68182,68182,68182,68182,68182,68518,68518,68518,68518,68518
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7120,7120,7120,7120,7120,7188,7188,7188,7188,7188
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,7808,7808,7808,7808,7808,7855,7855,7855,7855,7855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,12394,12394,12430,12430,12430,12437,12437,12437,12437,12437
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,11997,11997,12035,12035,12035,12045,12045,12045,12045,12045
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,6303,6303,6318,6318,6318,6333,6333,6333,6333,6333
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,2717,2717,2727,2727,2727,2731,2731,2731,2731,2731
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,1876,1876,1880,1880,1880,1881,1881,1881,1881,1881

Reading deaths csv file and displaying the deaths dataframe

In [3]:
covid_deaths = pd.read_csv("../../../data/Stage_1/covid_deaths_usafacts.csv")
covid_deaths

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-07,2023-01-08,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-14,2023-01-15,2023-01-16
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,719,721,721,721,721,721
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,103
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,136
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,16
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,43
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,47
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,22

Reading population csv file and displaying the population dataframe

In [4]:
covid_county_population = pd.read_csv("../../../data/Stage_1/covid_county_population_usafacts.csv")
covid_county_population

      countyFIPS            County Name State  population
0              0  Statewide Unallocated    AL           0
1           1001         Autauga County    AL       55869
2           1003         Baldwin County    AL      223234
3           1005         Barbour County    AL       24686
4           1007            Bibb County    AL       22394
...          ...                    ...   ...         ...
3190       56037      Sweetwater County    WY       42343
3191       56039           Teton County    WY       23464
3192       56041           Uinta County    WY       20226
3193       56043        Washakie County    WY        7805
3194       56045          Weston County    WY        6927

[3195 rows x 4 columns]

Data types of covid_cases dataframe

In [5]:
covid_cases.dtypes

countyFIPS      int64
County Name    object
State          object
StateFIPS       int64
2020-01-22      int64
                ...
2023-01-12      int64
2023-01-13      int64
2023-01-14      int64
2023-01-15      int64
2023-01-16      int64
Length: 1095, dtype: object

Data types of covid_deaths dataframe

In [6]:
covid_deaths.dtypes

countyFIPS      int64
County Name    object
State          object
StateFIPS       int64
2020-01-22      int64
                ...
2023-01-12      int64
2023-01-13      int64
2023-01-14      int64
2023-01-15      int64
2023-01-16      int64
Length: 1095, dtype: object

Data types of county population dataframe

In [7]:
covid_county_population.dtypes

countyFIPS      int64
County Name    object
State          object
population      int64
dtype: object

Merging covid_cases and covid_deaths dataframes into cases_deaths dataframe on common columns countyFIPS, County Name, State, StateFIPS.

In [8]:
cases_deaths = pd.merge(covid_cases, covid_deaths, on = ["countyFIPS",'County Name', "State", "StateFIPS"])
cases_deaths

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-07_y,2023-01-08_y,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,719,721,721,721,721,721
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,103
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,136
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,16
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,43
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,47
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,22

Merging cases_deaths and covid_county_population dataframes into super_covid19 dataframe on columns countyFIPS, State

In [9]:
super_covid19 = pd.merge(cases_deaths, covid_county_population, on = ["countyFIPS","State"])
super_covid19

,countyFIPS,County Name_x,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,County Name_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Statewide Unallocated,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,721,721,721,721,721,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,Bibb County,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,Weston County,6927

The super_covid19 dataframe is exported as super_covid19.csv file

In [10]:
super_covid19.to_csv("../../../data/Stage_1/super_covid19.csv", index = False)