Importing pandas library

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

Reading census demographic csv file and displaying the dataframe

In [2]:
census_demographic = pd.read_csv("../../../../data/Stage_1/ACSDP5Y2021.DP05-Data.csv", low_memory= False)
census_demographic

,GEO_ID,NAME,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0002E,DP05_0002M,DP05_0002MA,DP05_0002EA,...,DP05_0087PEA,DP05_0088PE,DP05_0088PM,DP05_0088PMA,DP05_0088PEA,DP05_0089PE,DP05_0089PM,DP05_0089PMA,DP05_0089PEA,Unnamed: 714
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Annotation of Estimate!!SEX AND AGE!!Total pop...,Margin of Error!!SEX AND AGE!!Total population,Annotation of Margin of Error!!SEX AND AGE!!To...,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Annotation of Margin of Error!!SEX AND AGE!!To...,Annotation of Estimate!!SEX AND AGE!!Total pop...,...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",Annotation of Percent Margin of Error!!CITIZEN...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",Annotation of Percent Margin of Error!!CITIZEN...,"Annotation of Percent!!CITIZEN, VOTING AGE POP...",NaN
1,0500000US01001,"Autauga County, Alabama",58239,NaN,*****,*****,28206,213,NaN,NaN,...,NaN,47.9,0.3,NaN,NaN,52.1,0.3,NaN,NaN,NaN
2,0500000US01003,"Baldwin County, Alabama",227131,NaN,*****,*****,110781,196,NaN,NaN,...,NaN,48.0,0.1,NaN,NaN,52.0,0.1,NaN,NaN,NaN
3,0500000US01005,"Barbour County, Alabama",25259,NaN,*****,*****,13361,63,NaN,NaN,...,NaN,53.9,0.4,NaN,NaN,46.1,0.4,NaN,NaN,NaN
4,0500000US01007,"Bibb County, Alabama",22412,NaN,*****,*****,12300,150,NaN,NaN,...,NaN,54.8,0.4,NaN,NaN,45.2,0.4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72145,"Vega Baja Municipio, Puerto Rico",54544,NaN,*****,*****,26057,*****,*****,NaN,...,NaN,46.9,0.1,NaN,NaN,53.1,0.1,NaN,NaN,NaN
3218,0500000US72147,"Vieques Municipio, Puerto Rico",8317,NaN,*****,*****,4239,166,NaN,NaN,...,NaN,50.2,0.3,NaN,NaN,49.8,0.3,NaN,NaN,NaN
3219,0500000US72149,"Villalba Municipio, Puerto Rico",22341,NaN,*****,*****,10796,*****,*****,NaN,...,NaN,47.5,0.1,NaN,NaN,52.5,0.1,NaN,NaN,NaN
3220,0500000US72151,"Yabucoa Municipio, Puerto Rico",31047,NaN,*****,*****,15000,*****,*****,NaN,...,NaN,47.5,0.2,NaN,NaN,52.5,0.2,NaN,NaN,NaN
3221,0500000US72153,"Yauco Municipio, Puerto Rico",34704,NaN,*****,*****,16548,*****,*****,NaN,...,NaN,46.8,0.1,NaN,NaN,53.2,0.1,NaN,NaN,NaN

In [3]:
census_demographic.drop(index= 0, inplace = True)   # dropping the zeroth row as it contains only titles
census_demographic

,GEO_ID,NAME,DP05_0001E,DP05_0001EA,DP05_0001M,DP05_0001MA,DP05_0002E,DP05_0002M,DP05_0002MA,DP05_0002EA,...,DP05_0087PEA,DP05_0088PE,DP05_0088PM,DP05_0088PMA,DP05_0088PEA,DP05_0089PE,DP05_0089PM,DP05_0089PMA,DP05_0089PEA,Unnamed: 714
1,0500000US01001,"Autauga County, Alabama",58239,NaN,*****,*****,28206,213,NaN,NaN,...,NaN,47.9,0.3,NaN,NaN,52.1,0.3,NaN,NaN,NaN
2,0500000US01003,"Baldwin County, Alabama",227131,NaN,*****,*****,110781,196,NaN,NaN,...,NaN,48.0,0.1,NaN,NaN,52.0,0.1,NaN,NaN,NaN
3,0500000US01005,"Barbour County, Alabama",25259,NaN,*****,*****,13361,63,NaN,NaN,...,NaN,53.9,0.4,NaN,NaN,46.1,0.4,NaN,NaN,NaN
4,0500000US01007,"Bibb County, Alabama",22412,NaN,*****,*****,12300,150,NaN,NaN,...,NaN,54.8,0.4,NaN,NaN,45.2,0.4,NaN,NaN,NaN
5,0500000US01009,"Blount County, Alabama",58884,NaN,*****,*****,29530,144,NaN,NaN,...,NaN,49.4,0.3,NaN,NaN,50.6,0.3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72145,"Vega Baja Municipio, Puerto Rico",54544,NaN,*****,*****,26057,*****,*****,NaN,...,NaN,46.9,0.1,NaN,NaN,53.1,0.1,NaN,NaN,NaN
3218,0500000US72147,"Vieques Municipio, Puerto Rico",8317,NaN,*****,*****,4239,166,NaN,NaN,...,NaN,50.2,0.3,NaN,NaN,49.8,0.3,NaN,NaN,NaN
3219,0500000US72149,"Villalba Municipio, Puerto Rico",22341,NaN,*****,*****,10796,*****,*****,NaN,...,NaN,47.5,0.1,NaN,NaN,52.5,0.1,NaN,NaN,NaN
3220,0500000US72151,"Yabucoa Municipio, Puerto Rico",31047,NaN,*****,*****,15000,*****,*****,NaN,...,NaN,47.5,0.2,NaN,NaN,52.5,0.2,NaN,NaN,NaN
3221,0500000US72153,"Yauco Municipio, Puerto Rico",34704,NaN,*****,*****,16548,*****,*****,NaN,...,NaN,46.8,0.1,NaN,NaN,53.2,0.1,NaN,NaN,NaN

Removing unwanted columns from the dataframe as it doesn't contribute to any covid analysis

In [4]:
census_demographic.drop(census_demographic.columns[census_demographic.columns.str.contains('EA')], axis= 1, inplace = True)
census_demographic.drop(census_demographic.columns[census_demographic.columns.str.endswith('M')], axis=1, inplace = True)
census_demographic.drop(census_demographic.columns[census_demographic.columns.str.contains('MA')], axis = 1, inplace= True)
census_demographic.drop(census_demographic.columns[census_demographic.columns.str.contains('PE')], axis = 1, inplace= True)
census_demographic.drop(census_demographic.columns[census_demographic.columns.str.contains('Unnamed')], axis = 1, inplace= True)
census_demographic

,GEO_ID,NAME,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,...,DP05_0080E,DP05_0081E,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E
1,0500000US01001,"Autauga County, Alabama",58239,28206,30033,93.9,3318,3716,4004,3939,...,647,0,109,1575,377,1198,24170,43906,21018,22888
2,0500000US01003,"Baldwin County, Alabama",227131,110781,116350,95.2,12035,11730,16407,13801,...,2175,9,959,4981,614,4367,121763,174686,83847,90839
3,0500000US01005,"Barbour County, Alabama",25259,13361,11898,112.3,1320,1601,1422,1487,...,106,1,229,474,92,382,11667,19623,10571,9052
4,0500000US01007,"Bibb County, Alabama",22412,12300,10112,121.6,1196,1274,1230,1463,...,46,0,18,192,22,170,9013,17682,9690,7992
5,0500000US01009,"Blount County, Alabama",58884,29530,29354,100.6,3467,3578,4194,3591,...,216,74,92,1479,466,1013,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72145,"Vega Baja Municipio, Puerto Rico",54544,26057,28487,91.5,2192,2611,3113,3440,...,0,0,132,0,0,0,24695,44370,20815,23555
3218,0500000US72147,"Vieques Municipio, Puerto Rico",8317,4239,4078,103.9,401,391,379,590,...,0,0,0,97,97,0,4967,6734,3378,3356
3219,0500000US72149,"Villalba Municipio, Puerto Rico",22341,10796,11545,93.5,1002,1363,1271,1549,...,0,0,9,0,0,0,9380,17807,8466,9341
3220,0500000US72151,"Yabucoa Municipio, Puerto Rico",31047,15000,16047,93.5,1092,1457,1816,1950,...,11,0,0,0,0,0,14548,25441,12091,13350
3221,0500000US72153,"Yauco Municipio, Puerto Rico",34704,16548,18156,91.1,1226,1655,2019,2044,...,0,0,114,73,73,0,17713,28529,13355,15174

Data types of census demographic dataframe

In [5]:
census_demographic.dtypes

GEO_ID        object
NAME          object
DP05_0001E    object
DP05_0002E    object
DP05_0003E    object
               ...
DP05_0085E    object
DP05_0086E    object
DP05_0087E    object
DP05_0088E    object
DP05_0089E    object
Length: 91, dtype: object

In order to merge with super covid19 dataframe we need to find the common columns in both dataframes. If we observe GEO_ID column of census dataframe we can see that it contains unique five digit countyFIPS in it.

In [6]:
#slicing the GEO_ID from 9th inorder to obtain countyFIPS
census_demographic['GEO_ID']= census_demographic['GEO_ID'].str.slice(9) 
#changing the datatype of GEO_ID to int64 as it should match with the super_covid19 column
census_demographic['GEO_ID']= census_demographic['GEO_ID'].astype('int64') 
#Renaming the GEO_ID to countyFIPS as it should match with the countyFIPS column in the super_covid19 dataframe
census_demographic.rename(columns = {'GEO_ID':'countyFIPS'}, inplace = True) 
#Removing the extra rows as it doesnt match with the covid19 dataset
census_demographic = census_demographic[census_demographic['countyFIPS'] < 72001] 
census_demographic

,countyFIPS,NAME,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,...,DP05_0080E,DP05_0081E,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E
1,1001,"Autauga County, Alabama",58239,28206,30033,93.9,3318,3716,4004,3939,...,647,0,109,1575,377,1198,24170,43906,21018,22888
2,1003,"Baldwin County, Alabama",227131,110781,116350,95.2,12035,11730,16407,13801,...,2175,9,959,4981,614,4367,121763,174686,83847,90839
3,1005,"Barbour County, Alabama",25259,13361,11898,112.3,1320,1601,1422,1487,...,106,1,229,474,92,382,11667,19623,10571,9052
4,1007,"Bibb County, Alabama",22412,12300,10112,121.6,1196,1274,1230,1463,...,46,0,18,192,22,170,9013,17682,9690,7992
5,1009,"Blount County, Alabama",58884,29530,29354,100.6,3467,3578,4194,3591,...,216,74,92,1479,466,1013,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,"Sweetwater County, Wyoming",42459,21850,20609,106.0,2657,3456,3008,3017,...,448,14,160,828,271,557,19174,30055,15515,14540
3140,56039,"Teton County, Wyoming",23319,12280,11039,111.2,1068,1032,1475,1144,...,369,15,154,463,207,256,13255,17273,9135,8138
3141,56041,"Uinta County, Wyoming",20514,10437,10077,103.6,1413,1712,1762,1327,...,37,0,0,571,58,513,8819,14203,7206,6997
3142,56043,"Washakie County, Wyoming",7768,4004,3764,106.4,399,321,606,633,...,31,0,32,207,16,191,3842,5993,3013,2980
3143,56045,"Weston County, Wyoming",6891,3684,3207,114.9,308,542,227,540,...,52,70,7,448,172,276,3431,5413,2848,2565

If we observe the NAME column in census_demographic dataframe it contains both county name and state. Splitting them at comma using the split function.

In [7]:
census_demographic[['County Name','State']]= census_demographic['NAME'].str.split(',',1, expand= True)
#Removing the unwanted spaces to the left and right of the State
census_demographic['State'] = census_demographic['State'].str.strip() 
census_demographic

,countyFIPS,NAME,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,...,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E,County Name,State
1,1001,"Autauga County, Alabama",58239,28206,30033,93.9,3318,3716,4004,3939,...,109,1575,377,1198,24170,43906,21018,22888,Autauga County,Alabama
2,1003,"Baldwin County, Alabama",227131,110781,116350,95.2,12035,11730,16407,13801,...,959,4981,614,4367,121763,174686,83847,90839,Baldwin County,Alabama
3,1005,"Barbour County, Alabama",25259,13361,11898,112.3,1320,1601,1422,1487,...,229,474,92,382,11667,19623,10571,9052,Barbour County,Alabama
4,1007,"Bibb County, Alabama",22412,12300,10112,121.6,1196,1274,1230,1463,...,18,192,22,170,9013,17682,9690,7992,Bibb County,Alabama
5,1009,"Blount County, Alabama",58884,29530,29354,100.6,3467,3578,4194,3591,...,92,1479,466,1013,24527,43633,21535,22098,Blount County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,"Sweetwater County, Wyoming",42459,21850,20609,106.0,2657,3456,3008,3017,...,160,828,271,557,19174,30055,15515,14540,Sweetwater County,Wyoming
3140,56039,"Teton County, Wyoming",23319,12280,11039,111.2,1068,1032,1475,1144,...,154,463,207,256,13255,17273,9135,8138,Teton County,Wyoming
3141,56041,"Uinta County, Wyoming",20514,10437,10077,103.6,1413,1712,1762,1327,...,0,571,58,513,8819,14203,7206,6997,Uinta County,Wyoming
3142,56043,"Washakie County, Wyoming",7768,4004,3764,106.4,399,321,606,633,...,32,207,16,191,3842,5993,3013,2980,Washakie County,Wyoming
3143,56045,"Weston County, Wyoming",6891,3684,3207,114.9,308,542,227,540,...,7,448,172,276,3431,5413,2848,2565,Weston County,Wyoming

In [8]:
state = census_demographic['State'].values[0]
state

'Alabama'

We need to replace the state names to two letter codes as it should match with State column in the super_covid19 dataset. Creating a dictionary which contains two letter code for each state

In [9]:
state_1 = {'Alabama' : 'AL','Alaska' : 'AK','Arkansas' : 'AR', 'American Samoa' : 'AS', 
           'Arizona' : 'AZ', 'California' : 'CA', 'Colorado' : 'CO', 'Connecticut' : 'CT', 
           'District of Columbia' : 'DC', 'Delaware' : 'DE', 'Florida' : 'FL',
           'Georgia' : 'GA', 'Guam' : 'GU', 'Hawaii' : 'HI', 'Iowa' : 'IA', 'Idaho' : 'ID', 
           'Illinois' : 'IL', 'Indiana' : 'IN','Kansas' : 'KS', 'Kentucky' : 'KY', 
           'Louisiana' : 'LA', 'Massachusetts' : 'MA', 'Maryland' : 'MD', 'Maine' : 'ME', 'Michigan' : 'MI',
           'Minnesota' : 'MN', 'Missouri' : 'MO', 'Northern Mariana Islands' : 'MP', 'Mississippi' : 'MS', 'Montana' : 'MT', 'National' : 'NA',
           'North Carolina' : 'NC', 'North Dakota' : 'ND', 'Nebraska' : 'NE', 'New Hampshire' : 'NH', 'New Jersey' : 'NJ',
           'New Mexico' : 'NM', 'Nevada' : 'NV', 'New York' : 'NY', 'Ohio' : 'OH', 'Oklahoma' : 'OK', 'Oregon' : 'OR', 'Pennsylvania' : 'PA',
           'Puerto Rico' : 'PR', 'Rhode Island' : 'RI', 'South Carolina' : 'SC', 'South Dakota' : 'SD', 'Tennessee' : 'TN',
           'Texas' : 'TX', 'Utah' : 'UT', 'Virginia' : 'VA', 'Virgin Islands' : 'VI', 'Vermont' : 'VT', 'Washington' : 'WA', 'Wisconsin' : 'WI',
           'West Virginia' : 'WV', 'Wyoming' : 'WY'}

Replacing the State name with the two letter code in the state column of the census_demographic dataframe

In [10]:
census_demographic['State'] = census_demographic.State.replace(state_1)
census_demographic

,countyFIPS,NAME,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,...,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E,County Name,State
1,1001,"Autauga County, Alabama",58239,28206,30033,93.9,3318,3716,4004,3939,...,109,1575,377,1198,24170,43906,21018,22888,Autauga County,AL
2,1003,"Baldwin County, Alabama",227131,110781,116350,95.2,12035,11730,16407,13801,...,959,4981,614,4367,121763,174686,83847,90839,Baldwin County,AL
3,1005,"Barbour County, Alabama",25259,13361,11898,112.3,1320,1601,1422,1487,...,229,474,92,382,11667,19623,10571,9052,Barbour County,AL
4,1007,"Bibb County, Alabama",22412,12300,10112,121.6,1196,1274,1230,1463,...,18,192,22,170,9013,17682,9690,7992,Bibb County,AL
5,1009,"Blount County, Alabama",58884,29530,29354,100.6,3467,3578,4194,3591,...,92,1479,466,1013,24527,43633,21535,22098,Blount County,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,"Sweetwater County, Wyoming",42459,21850,20609,106.0,2657,3456,3008,3017,...,160,828,271,557,19174,30055,15515,14540,Sweetwater County,WY
3140,56039,"Teton County, Wyoming",23319,12280,11039,111.2,1068,1032,1475,1144,...,154,463,207,256,13255,17273,9135,8138,Teton County,WY
3141,56041,"Uinta County, Wyoming",20514,10437,10077,103.6,1413,1712,1762,1327,...,0,571,58,513,8819,14203,7206,6997,Uinta County,WY
3142,56043,"Washakie County, Wyoming",7768,4004,3764,106.4,399,321,606,633,...,32,207,16,191,3842,5993,3013,2980,Washakie County,WY
3143,56045,"Weston County, Wyoming",6891,3684,3207,114.9,308,542,227,540,...,7,448,172,276,3431,5413,2848,2565,Weston County,WY

In [11]:
#Creating a copy of the dataframe
census_demographic_temp = census_demographic.copy() 
#Dropping the NAME column as we already got County Name and State columns from it
census_demographic_temp.drop('NAME',axis=1,inplace= True) 
census_demographic_temp

,countyFIPS,DP05_0001E,DP05_0002E,DP05_0003E,DP05_0004E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,...,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E,County Name,State
1,1001,58239,28206,30033,93.9,3318,3716,4004,3939,3648,...,109,1575,377,1198,24170,43906,21018,22888,Autauga County,AL
2,1003,227131,110781,116350,95.2,12035,11730,16407,13801,11181,...,959,4981,614,4367,121763,174686,83847,90839,Baldwin County,AL
3,1005,25259,13361,11898,112.3,1320,1601,1422,1487,1434,...,229,474,92,382,11667,19623,10571,9052,Barbour County,AL
4,1007,22412,12300,10112,121.6,1196,1274,1230,1463,1192,...,18,192,22,170,9013,17682,9690,7992,Bibb County,AL
5,1009,58884,29530,29354,100.6,3467,3578,4194,3591,3386,...,92,1479,466,1013,24527,43633,21535,22098,Blount County,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,42459,21850,20609,106.0,2657,3456,3008,3017,2505,...,160,828,271,557,19174,30055,15515,14540,Sweetwater County,WY
3140,56039,23319,12280,11039,111.2,1068,1032,1475,1144,941,...,154,463,207,256,13255,17273,9135,8138,Teton County,WY
3141,56041,20514,10437,10077,103.6,1413,1712,1762,1327,1067,...,0,571,58,513,8819,14203,7206,6997,Uinta County,WY
3142,56043,7768,4004,3764,106.4,399,321,606,633,386,...,32,207,16,191,3842,5993,3013,2980,Washakie County,WY
3143,56045,6891,3684,3207,114.9,308,542,227,540,382,...,7,448,172,276,3431,5413,2848,2565,Weston County,WY

Still the census_demographic contains more number of columns so for now, selecting the columns which will be helpful for the covid analysis. In future if required we can add or delete columns

In [12]:
census_demographic = census_demographic[['countyFIPS','County Name','State','DP05_0002E','DP05_0003E','DP05_0005E','DP05_0006E','DP05_0007E','DP05_0008E','DP05_0009E','DP05_0010E','DP05_0011E','DP05_0012E','DP05_0013E',
                                         'DP05_0014E','DP05_0015E','DP05_0016E','DP05_0017E','DP05_0019E','DP05_0021E',
                                        'DP05_0024E','DP05_0026E','DP05_0027E','DP05_0030E','DP05_0031E','DP05_0036E','DP05_0037E','DP05_0038E',
                                         'DP05_0044E','DP05_0086E','DP05_0087E','DP05_0088E','DP05_0089E']]
census_demographic

,countyFIPS,County Name,State,DP05_0002E,DP05_0003E,DP05_0005E,DP05_0006E,DP05_0007E,DP05_0008E,DP05_0009E,...,DP05_0030E,DP05_0031E,DP05_0036E,DP05_0037E,DP05_0038E,DP05_0044E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E
1,1001,Autauga County,AL,28206,30033,3318,3716,4004,3939,3648,...,3919,4896,56166,43755,11470,647,24170,43906,21018,22888
2,1003,Baldwin County,AL,110781,116350,12035,11730,16407,13801,11181,...,21795,25010,219535,192034,19895,2175,121763,174686,83847,90839
3,1005,Barbour County,AL,13361,11898,1320,1601,1422,1487,1434,...,2084,2717,24641,11495,11985,106,11667,19623,10571,9052
4,1007,Bibb County,AL,12300,10112,1196,1274,1230,1463,1192,...,1629,1965,22111,17020,5003,46,9013,17682,9690,7992
5,1009,Blount County,AL,29530,29354,3467,3578,4194,3591,3386,...,4726,5858,56921,54439,760,216,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,21850,20609,2657,3456,3008,3017,2505,...,2608,2782,39597,36867,525,487,19174,30055,15515,14540
3140,56039,Teton County,WY,12280,11039,1068,1032,1475,1144,941,...,1829,1780,22643,19873,166,369,13255,17273,9135,8138
3141,56041,Uinta County,WY,10437,10077,1413,1712,1762,1327,1067,...,1540,1482,19536,18899,52,37,8819,14203,7206,6997
3142,56043,Washakie County,WY,4004,3764,399,321,606,633,386,...,824,906,7328,6655,1,31,3842,5993,3013,2980
3143,56045,Weston County,WY,3684,3207,308,542,227,540,382,...,697,719,6406,6154,25,52,3431,5413,2848,2565

Renaming the selected columns for better understanding

In [13]:
census_demographic.rename(columns={'DP05_0002E':'Male population','DP05_0003E':'Female population','DP05_0005E':'Under 5years','DP05_0006E':'5 to 9years','DP05_0007E':'10 to 14years','DP05_0008E':'15 to 19years','DP05_0009E':'20 to 24years',
                                   'DP05_0010E':'25 to 34years','DP05_0011E':'35 to 44 years','DP05_0012E':'45 to 54years','DP05_0013E':'55 to 59years','DP05_0014E':'60 to 64years','DP05_0015E':'65 to 74years','DP05_0016E':'75 to 84years',
                                   'DP05_0017E':'85years and over','DP05_0019E':'Under 18years','DP05_0021E':'18years and above','DP05_0024E':'65years and above',
                                   'DP05_0026E':'Male(18years and above)','DP05_0027E':'Female(18years and above)','DP05_0030E':'Male(65years and above)','DP05_0031E':'Female(65years and over)','DP05_0036E':'One race population','DP05_0037E':'White population',
                                   'DP05_0038E':'Black population','DP05_0044E':'Asian population','DP05_0086E':'Total Housing units','DP05_0087E':'Voting population','DP05_0088E':'Male voting population','DP05_0089E':'Female voting population'}, inplace = True)
census_demographic

,countyFIPS,County Name,State,Male population,Female population,Under 5years,5 to 9years,10 to 14years,15 to 19years,20 to 24years,...,Male(65years and above),Female(65years and over),One race population,White population,Black population,Asian population,Total Housing units,Voting population,Male voting population,Female voting population
1,1001,Autauga County,AL,28206,30033,3318,3716,4004,3939,3648,...,3919,4896,56166,43755,11470,647,24170,43906,21018,22888
2,1003,Baldwin County,AL,110781,116350,12035,11730,16407,13801,11181,...,21795,25010,219535,192034,19895,2175,121763,174686,83847,90839
3,1005,Barbour County,AL,13361,11898,1320,1601,1422,1487,1434,...,2084,2717,24641,11495,11985,106,11667,19623,10571,9052
4,1007,Bibb County,AL,12300,10112,1196,1274,1230,1463,1192,...,1629,1965,22111,17020,5003,46,9013,17682,9690,7992
5,1009,Blount County,AL,29530,29354,3467,3578,4194,3591,3386,...,4726,5858,56921,54439,760,216,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3139,56037,Sweetwater County,WY,21850,20609,2657,3456,3008,3017,2505,...,2608,2782,39597,36867,525,487,19174,30055,15515,14540
3140,56039,Teton County,WY,12280,11039,1068,1032,1475,1144,941,...,1829,1780,22643,19873,166,369,13255,17273,9135,8138
3141,56041,Uinta County,WY,10437,10077,1413,1712,1762,1327,1067,...,1540,1482,19536,18899,52,37,8819,14203,7206,6997
3142,56043,Washakie County,WY,4004,3764,399,321,606,633,386,...,824,906,7328,6655,1,31,3842,5993,3013,2980
3143,56045,Weston County,WY,3684,3207,308,542,227,540,382,...,697,719,6406,6154,25,52,3431,5413,2848,2565

Storing the final census_demographic dataframe in the csv format for further usage

In [14]:
census_demographic.to_csv('../../../../data/Stage_1/census_demographic.csv',index= False)

Reading the generated super_covid19 dataset in the team task inorder to merge with the enrichment dataset

In [15]:
super_covid19 = pd.read_csv('../../../../data/Stage_1/super_covid19.csv')
super_covid19

,countyFIPS,County Name_x,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,County Name_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Statewide Unallocated,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,721,721,721,721,721,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,Bibb County,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,Weston County,6927

Renaming the County Name_x to County Name as the name should match for merging and dropping the County Name_y from the dataframe

In [16]:
super_covid19.rename(columns={'County Name_x':'County Name'},inplace = True)
super_covid19.drop('County Name_y',axis=1,inplace = True)
super_covid19

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-08_y,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,721,721,721,721,721,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,6927

Removing the unwanted spaces from the County Name if there exists any

In [17]:
super_covid19['County Name'] = super_covid19['County Name'].str.strip()
super_covid19

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-08_y,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,721,721,721,721,721,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,6927

Removing the rows whose county name is statewide unallocated

In [18]:
super_covid19 = super_covid19[super_covid19['County Name']!= 'Statewide Unallocated']
super_covid19

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-08_y,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,population
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,719,721,721,721,721,721,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,108,22394
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,260,260,260,260,261,261,261,261,261,57826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,136,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,16,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,43,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,47,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,22,6927

Removing unwanted spaces in county name column of census_demographic dataframe if there exists any

In [19]:
census_demographic_temp['County Name'] = census_demographic_temp['County Name'].str.strip()
census_demographic['County Name'] = census_demographic['County Name'].str.strip()

Merging the super_covid19 dataframe and census_demographic_temp dataframe on countyFIPS, County Name, State columns as they are common in both dataframes

In [20]:
covid_census_temp = pd.merge(super_covid19,census_demographic_temp,on = ['countyFIPS','County Name','State'])
covid_census_temp

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,DP05_0080E,DP05_0081E,DP05_0082E,DP05_0083E,DP05_0084E,DP05_0085E,DP05_0086E,DP05_0087E,DP05_0088E,DP05_0089E
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,647,0,109,1575,377,1198,24170,43906,21018,22888
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,2175,9,959,4981,614,4367,121763,174686,83847,90839
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,106,1,229,474,92,382,11667,19623,10571,9052
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,46,0,18,192,22,170,9013,17682,9690,7992
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,216,74,92,1479,466,1013,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3081,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,448,14,160,828,271,557,19174,30055,15515,14540
3082,56039,Teton County,WY,56,0,0,0,0,0,0,...,369,15,154,463,207,256,13255,17273,9135,8138
3083,56041,Uinta County,WY,56,0,0,0,0,0,0,...,37,0,0,571,58,513,8819,14203,7206,6997
3084,56043,Washakie County,WY,56,0,0,0,0,0,0,...,31,0,32,207,16,191,3842,5993,3013,2980
3085,56045,Weston County,WY,56,0,0,0,0,0,0,...,52,70,7,448,172,276,3431,5413,2848,2565

Merging the super_covid19 dataframe and census_demographic dataframe on countyFIPS, County Name and State columns as they are common in both

In [21]:
covid_census = pd.merge(super_covid19,census_demographic,on = ['countyFIPS','County Name','State'])
covid_census

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,Male(65years and above),Female(65years and over),One race population,White population,Black population,Asian population,Total Housing units,Voting population,Male voting population,Female voting population
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,3919,4896,56166,43755,11470,647,24170,43906,21018,22888
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,21795,25010,219535,192034,19895,2175,121763,174686,83847,90839
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,2084,2717,24641,11495,11985,106,11667,19623,10571,9052
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,1629,1965,22111,17020,5003,46,9013,17682,9690,7992
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,4726,5858,56921,54439,760,216,24527,43633,21535,22098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3081,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,2608,2782,39597,36867,525,487,19174,30055,15515,14540
3082,56039,Teton County,WY,56,0,0,0,0,0,0,...,1829,1780,22643,19873,166,369,13255,17273,9135,8138
3083,56041,Uinta County,WY,56,0,0,0,0,0,0,...,1540,1482,19536,18899,52,37,8819,14203,7206,6997
3084,56043,Washakie County,WY,56,0,0,0,0,0,0,...,824,906,7328,6655,1,31,3842,5993,3013,2980
3085,56045,Weston County,WY,56,0,0,0,0,0,0,...,697,719,6406,6154,25,52,3431,5413,2848,2565

Exporting the merged covid_census dataframe in the csv format

In [22]:
covid_census.to_csv('../../../../data/Stage_1/covid_census.csv',index= False)

In [25]:
census_demographic.dtypes

countyFIPS                    int64
County Name                  object
State                        object
Male population              object
Female population            object
Under 5years                 object
5 to 9years                  object
10 to 14years                object
15 to 19years                object
20 to 24years                object
25 to 34years                object
35 to 44 years               object
45 to 54years                object
55 to 59years                object
60 to 64years                object
65 to 74years                object
75 to 84years                object
85years and over             object
Under 18years                object
18years and above            object
65years and above            object
Male(18years and above)      object
Female(18years and above)    object
Male(65years and above)      object
Female(65years and over)     object
One race population          object
White population             object
Black population             object
Asian population             object
Total Housing units          object
Voting population            object
Male voting population       object
Female voting population     object
dtype: object