# Task 3

Importing pandas library

In [89]:
import pandas as pd

Reading super covid csv file and displaying the dataframe

In [90]:
super_covid_df = pd.read_csv("/Users/anshu/Desktop/Courses/Data Science/Project Stage - I/super_covid19.csv", low_memory= False)
super_covid_df.rename(columns={'County Name_x':'County Name'},inplace = True)
super_covid_df

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,County Name_y,population
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Statewide Unallocated,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,721,721,721,721,721,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,Bibb County,22394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,Weston County,6927

Removing all 52 Statewise unallocated row as they are not required

In [91]:
super_covid_df = super_covid_df[~super_covid_df['County Name'].str.contains('Statewide Unallocated')]
for col in super_covid_df.columns:
    if super_covid_df[col].dtype == object:
        super_covid_df[col] = super_covid_df[col].str.strip()
super_covid_df

/var/folders/b1/1gnx6t993pd_mmbwzhgq9rz00000gn/T/ipykernel_2865/3850674251.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super_covid_df[col] = super_covid_df[col].str.strip()

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,2023-01-09_y,2023-01-10_y,2023-01-11_y,2023-01-12_y,2023-01-13_y,2023-01-14_y,2023-01-15_y,2023-01-16_y,County Name_y,population
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,Autauga County,55869
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,719,719,719,721,721,721,721,721,Baldwin County,223234
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,Barbour County,24686
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,108,108,108,108,108,108,108,108,Bibb County,22394
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,260,260,260,261,261,261,261,261,Blount County,57826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,136,136,136,136,136,136,136,136,Sweetwater County,42343
3189,56039,Teton County,WY,56,0,0,0,0,0,0,...,16,16,16,16,16,16,16,16,Teton County,23464
3190,56041,Uinta County,WY,56,0,0,0,0,0,0,...,43,43,43,43,43,43,43,43,Uinta County,20226
3191,56043,Washakie County,WY,56,0,0,0,0,0,0,...,47,47,47,47,47,47,47,47,Washakie County,7805
3192,56045,Weston County,WY,56,0,0,0,0,0,0,...,22,22,22,22,22,22,22,22,Weston County,6927

Reading ecnomic dataset csv file and displaying the dataframe

In [92]:
economic_df = pd.read_csv("/Users/anshu/Desktop/Courses/Data Science/Project Stage - I/DP03/ACSDP5Y2021_DP03-RawData.csv", low_memory= False)
economic_df

,GEO_ID,NAME,DP03_0001E,DP03_0001M,DP03_0001MA,DP03_0001EA,DP03_0002E,DP03_0002EA,DP03_0002M,DP03_0002MA,...,DP03_0135PM,DP03_0135PMA,DP03_0136PE,DP03_0136PM,DP03_0136PMA,DP03_0136PEA,DP03_0137PE,DP03_0137PM,DP03_0137PMA,DP03_0137PEA
0,Geography,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Annotation of Estimate!!EMPLOYMENT STATUS!!Pop...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Annotation of Margin of Error!!EMPLOYMENT STAT...,...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Annotation of Percent Margin of Error!!PERCENT...,Annotation of Percent!!PERCENTAGE OF FAMILIES ...
1,0500000US01001,"Autauga County, Alabama",46577,284,NaN,NaN,27550,NaN,798,NaN,...,2.3,NaN,12,2.2,NaN,NaN,22.3,4,NaN,NaN
2,0500000US01003,"Baldwin County, Alabama",183804,442,NaN,NaN,108873,NaN,2168,NaN,...,1.1,NaN,6.5,1,NaN,NaN,22.5,2.4,NaN,NaN
3,0500000US01005,"Barbour County, Alabama",20639,80,NaN,NaN,9369,NaN,448,NaN,...,3.4,NaN,25.7,3.1,NaN,NaN,30.2,5.6,NaN,NaN
4,0500000US01007,"Bibb County, Alabama",18333,164,NaN,NaN,9107,NaN,579,NaN,...,2.9,NaN,14.6,3.7,NaN,NaN,32.2,8.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72145,"Vega Baja Municipio, Puerto Rico",45974,184,NaN,NaN,19808,NaN,771,NaN,...,3.8,NaN,39.7,3.4,NaN,NaN,60.2,4.4,NaN,NaN
3218,0500000US72147,"Vieques Municipio, Puerto Rico",7041,178,NaN,NaN,2355,NaN,463,NaN,...,12.4,NaN,53,10.6,NaN,NaN,54.1,14.2,NaN,NaN
3219,0500000US72149,"Villalba Municipio, Puerto Rico",18348,100,NaN,NaN,7858,NaN,495,NaN,...,5,NaN,41.4,4.7,NaN,NaN,63.1,5.8,NaN,NaN
3220,0500000US72151,"Yabucoa Municipio, Puerto Rico",26282,169,NaN,NaN,9897,NaN,655,NaN,...,4.1,NaN,49.4,4.6,NaN,NaN,67,5.7,NaN,NaN
3221,0500000US72153,"Yauco Municipio, Puerto Rico",29486,99,NaN,NaN,11471,NaN,536,NaN,...,4.5,NaN,41.2,3.8,NaN,NaN,70.4,4.8,NaN,NaN

Removing columns with NaN values

In [93]:
# find and drop the column names that contain the 'MA' text
columns_to_drop = [col for col in economic_df.columns if "MA" in col]
economic_df = economic_df.drop(columns_to_drop, axis=1)

# find and drop the column names that end with the letter 'M'
columns_to_drop2 = [col for col in economic_df.columns if col[-1] == 'M']
economic_df = economic_df.drop(columns_to_drop2, axis=1)

# find and drop the column names that contain the 'EA' text
columns_to_drop3 = [col for col in economic_df.columns if "EA" in col]
economic_df = economic_df.drop(columns_to_drop3, axis=1)

economic_df

,GEO_ID,NAME,DP03_0001E,DP03_0002E,DP03_0003E,DP03_0004E,DP03_0005E,DP03_0006E,DP03_0007E,DP03_0008E,...,DP03_0128PE,DP03_0129PE,DP03_0130PE,DP03_0131PE,DP03_0132PE,DP03_0133PE,DP03_0134PE,DP03_0135PE,DP03_0136PE,DP03_0137PE
0,Geography,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Estimate!!EMPLOYMENT STATUS!!Civilian labor force,...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...,Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHO...
1,0500000US01001,"Autauga County, Alabama",46577,27550,26623,25871,752,927,19027,26623,...,13.6,18.7,18.5,18.7,18.4,12,13.2,6.9,12,22.3
2,0500000US01003,"Baldwin County, Alabama",183804,108873,108361,104367,3994,512,74931,108361,...,9.2,11.3,11.1,10.5,11.3,8.6,9.2,7,6.5,22.5
3,0500000US01005,"Barbour County, Alabama",20639,9369,9369,8561,808,0,11270,9369,...,26.5,43.7,43.7,55,39.8,21.2,23.6,14.4,25.7,30.2
4,0500000US01007,"Bibb County, Alabama",18333,9107,9107,8223,884,0,9226,9107,...,16.9,28,27.6,17.1,31.4,13.9,16.4,4.5,14.6,32.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,0500000US72145,"Vega Baja Municipio, Puerto Rico",45974,19808,19789,16307,3482,19,26166,19789,...,43.4,52.8,52.8,64.3,49.6,41.3,41.1,41.8,39.7,60.2
3218,0500000US72147,"Vieques Municipio, Puerto Rico",7041,2355,2355,1997,358,0,4686,2355,...,53.2,86,86,100,81.1,45.7,44.8,47.8,53,54.1
3219,0500000US72149,"Villalba Municipio, Puerto Rico",18348,7858,7856,6392,1464,2,10490,7856,...,44.5,55.4,55.2,62.9,53,41.8,42.9,38.2,41.4,63.1
3220,0500000US72151,"Yabucoa Municipio, Puerto Rico",26282,9897,9897,8391,1506,0,16385,9897,...,52.6,66.1,66.1,72,64.7,49.7,50,48.8,49.4,67
3221,0500000US72153,"Yauco Municipio, Puerto Rico",29486,11471,11471,9479,1992,0,18015,11471,...,46.4,56,55.6,33.2,61.3,44.4,42.6,48.9,41.2,70.4

Removing row 0
Extracting countyFIPS from GEO_ID by splitting at S
Splitting county and state name by splitting from ,

In [94]:
#removing 0th row
economic_df = economic_df.drop(economic_df.index[0])

#Extracting countyFIPS from GEO_ID by splitting at S
economic_df[['col1', 'countyFIPS']] = economic_df['GEO_ID'].str.split("S", expand=True)
economic_df = economic_df.drop('GEO_ID', axis=1)
economic_df = economic_df.drop('col1', axis=1)

#Splitting county and state name by splitting from ,
economic_df[['County Name', 'State']] = economic_df['NAME'].str.split(",", expand=True)
economic_df = economic_df.drop('NAME', axis=1)

#removing any extra spaces
for col in economic_df.columns:
    if economic_df[col].dtype == object:
        economic_df[col] = economic_df[col].str.strip()

economic_df

,DP03_0001E,DP03_0002E,DP03_0003E,DP03_0004E,DP03_0005E,DP03_0006E,DP03_0007E,DP03_0008E,DP03_0009E,DP03_0010E,...,DP03_0131PE,DP03_0132PE,DP03_0133PE,DP03_0134PE,DP03_0135PE,DP03_0136PE,DP03_0137PE,countyFIPS,County Name,State
1,46577,27550,26623,25871,752,927,19027,26623,(X),24292,...,18.7,18.4,12,13.2,6.9,12,22.3,01001,Autauga County,Alabama
2,183804,108873,108361,104367,3994,512,74931,108361,(X),95327,...,10.5,11.3,8.6,9.2,7,6.5,22.5,01003,Baldwin County,Alabama
3,20639,9369,9369,8561,808,0,11270,9369,(X),9599,...,55,39.8,21.2,23.6,14.4,25.7,30.2,01005,Barbour County,Alabama
4,18333,9107,9107,8223,884,0,9226,9107,(X),8239,...,17.1,31.4,13.9,16.4,4.5,14.6,32.2,01007,Bibb County,Alabama
5,46871,25844,25798,24244,1554,46,21027,25798,(X),23482,...,18.7,16.2,12,11.4,14.2,10,33.3,01009,Blount County,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,45974,19808,19789,16307,3482,19,26166,19789,(X),24274,...,64.3,49.6,41.3,41.1,41.8,39.7,60.2,72145,Vega Baja Municipio,Puerto Rico
3218,7041,2355,2355,1997,358,0,4686,2355,(X),3483,...,100,81.1,45.7,44.8,47.8,53,54.1,72147,Vieques Municipio,Puerto Rico
3219,18348,7858,7856,6392,1464,2,10490,7856,(X),9556,...,62.9,53,41.8,42.9,38.2,41.4,63.1,72149,Villalba Municipio,Puerto Rico
3220,26282,9897,9897,8391,1506,0,16385,9897,(X),13701,...,72,64.7,49.7,50,48.8,49.4,67,72151,Yabucoa Municipio,Puerto Rico
3221,29486,11471,11471,9479,1992,0,18015,11471,(X),15598,...,33.2,61.3,44.4,42.6,48.9,41.2,70.4,72153,Yauco Municipio,Puerto Rico

Selecting the columns which will be useful for covid analysis

In [95]:
economic_df = economic_df[['countyFIPS','County Name','State', 'DP03_0001E', 'DP03_0010E', 'DP03_0021E', 'DP03_0024E', 'DP03_0029E', 'DP03_0042E', 'DP03_0048E', 'DP03_0050E', 
                         'DP03_0052E', 'DP03_0061E', 'DP03_0086E', 'DP03_0097E','DP03_0099E', 'DP03_0106E', 'DP03_0108E', 'DP03_0134E', 'DP03_0135E']]

economic_df

,countyFIPS,County Name,State,DP03_0001E,DP03_0010E,DP03_0021E,DP03_0024E,DP03_0029E,DP03_0042E,DP03_0048E,DP03_0050E,DP03_0052E,DP03_0061E,DP03_0086E,DP03_0097E,DP03_0099E,DP03_0106E,DP03_0108E,DP03_0134E,DP03_0135E
1,01001,Autauga County,Alabama,46577,24292,144,1254,5656,5216,5155,21,1213,1022,72441,40853,4496,21383,2441,(X),(X)
2,01003,Baldwin County,Alabama,183804,95327,133,8013,24673,19718,14172,131,4251,6183,82801,156322,21826,78564,12797,(X),(X)
3,01005,Barbour County,Alabama,20639,9599,7,137,1700,1562,1817,23,1120,299,48768,11636,2313,6163,989,(X),(X)
4,01007,Bibb County,Alabama,18333,8239,0,368,1770,1746,948,0,528,234,67979,13148,2095,6435,973,(X),(X)
5,01009,Blount County,Alabama,46871,23482,30,678,5228,5170,2795,73,1784,791,68945,38181,5854,19078,2540,(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,72145,Vega Baja Municipio,Puerto Rico,45974,24274,91,328,4136,3504,2857,23,4631,107,25851,17894,5212,8611,2150,(X),(X)
3218,72147,Vieques Municipio,Puerto Rico,7041,3483,30,495,205,327,946,0,654,0,19683,1809,1136,514,421,(X),(X)
3219,72149,Villalba Municipio,Puerto Rico,18348,9556,30,17,1112,1568,1763,0,1956,41,24328,6397,707,2771,307,(X),(X)
3220,72151,Yabucoa Municipio,Puerto Rico,26282,13701,0,1,1870,1760,1856,0,3484,0,23274,7815,1747,3915,1010,(X),(X)
3221,72153,Yauco Municipio,Puerto Rico,29486,15598,49,469,2440,2579,2434,0,3898,23,23833,11887,2036,5692,614,(X),(X)

Renaming the columns name and changing datatype of countyFIPS to int64 for merging with super covid dataset

In [103]:
economic_df.rename(columns={'State' : 'State_USA',
                            'DP03_0001E' : ' Employment Status-Employed(Above 16 years)', 
                            'DP03_0010E' : 'Employment Status-Employed(Female)', 
                            'DP03_0021E' : ' Commuting to work with Public transport', 
                            'DP03_0024E' : 'Working from home', 
                            'DP03_0029E' : ' Occupation-Sales and office occupations',
                            'DP03_0042E' : ' Industry-Educational services, and health care and social assistance',
                            'DP03_0048E' : 'Class of worker-Government workers', 
                            'DP03_0050E' : 'Unpaid family workers', 
                            'DP03_0052E' : 'Income-Less than $10,000', 
                            'DP03_0061E' : 'Income-$200,000 or more', 
                            'DP03_0086E' : 'Median family income', 
                            'DP03_0097E' : 'With private health insurance',
                            'DP03_0099E' : 'No health insurance coverage', 
                            'DP03_0106E' : 'With private health insurance(Employed noninstitutionalized population 19 to 64 years)', 
                            'DP03_0108E' : 'No health insurance coverage(Employed noninstitutionalized population 19 to 64 years)', 
                            'DP03_0134E' : '18 to 64 years (People whose income in past 12 years is below poverty level)', 
                            'DP03_0135E' : '65 years and over (People whose income in past 12 years is below poverty level)'},
          inplace=True)
economic_df['countyFIPS'] = economic_df['countyFIPS'].astype('int64')
economic_df

/var/folders/b1/1gnx6t993pd_mmbwzhgq9rz00000gn/T/ipykernel_2865/4147210580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  economic_df.rename(columns={'State' : 'State_USA',
/var/folders/b1/1gnx6t993pd_mmbwzhgq9rz00000gn/T/ipykernel_2865/4147210580.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  economic_df['countyFIPS'] = economic_df['countyFIPS'].astype('int64')

,countyFIPS,County Name,State_USA,Employment Status-Employed(Above 16 years),Employment Status-Employed(Female),Commuting to work with Public transport,Working from home,Occupation-Sales and office occupations,"Industry-Educational services, and health care and social assistance",Class of worker-Government workers,Unpaid family workers,"Income-Less than $10,000","Income-$200,000 or more",Median family income,With private health insurance,No health insurance coverage,With private health insurance(Employed noninstitutionalized population 19 to 64 years),No health insurance coverage(Employed noninstitutionalized population 19 to 64 years),18 to 64 years (People whose income in past 12 years is below poverty level),65 years and over (People whose income in past 12 years is below poverty level)
1,1001,Autauga County,Alabama,46577,24292,144,1254,5656,5216,5155,21,1213,1022,72441,40853,4496,21383,2441,(X),(X)
2,1003,Baldwin County,Alabama,183804,95327,133,8013,24673,19718,14172,131,4251,6183,82801,156322,21826,78564,12797,(X),(X)
3,1005,Barbour County,Alabama,20639,9599,7,137,1700,1562,1817,23,1120,299,48768,11636,2313,6163,989,(X),(X)
4,1007,Bibb County,Alabama,18333,8239,0,368,1770,1746,948,0,528,234,67979,13148,2095,6435,973,(X),(X)
5,1009,Blount County,Alabama,46871,23482,30,678,5228,5170,2795,73,1784,791,68945,38181,5854,19078,2540,(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,72145,Vega Baja Municipio,Puerto Rico,45974,24274,91,328,4136,3504,2857,23,4631,107,25851,17894,5212,8611,2150,(X),(X)
3218,72147,Vieques Municipio,Puerto Rico,7041,3483,30,495,205,327,946,0,654,0,19683,1809,1136,514,421,(X),(X)
3219,72149,Villalba Municipio,Puerto Rico,18348,9556,30,17,1112,1568,1763,0,1956,41,24328,6397,707,2771,307,(X),(X)
3220,72151,Yabucoa Municipio,Puerto Rico,26282,13701,0,1,1870,1760,1856,0,3484,0,23274,7815,1747,3915,1010,(X),(X)
3221,72153,Yauco Municipio,Puerto Rico,29486,15598,49,469,2440,2579,2434,0,3898,23,23833,11887,2036,5692,614,(X),(X)

merging super covid with enrichment dataset

In [104]:
super_covid_df.dtypes

countyFIPS        int64
County Name      object
State            object
StateFIPS         int64
2020-01-22_x      int64
                  ...
2023-01-14_y      int64
2023-01-15_y      int64
2023-01-16_y      int64
County Name_y    object
population        int64
Length: 2188, dtype: object

In [105]:
economic_df.dtypes

countyFIPS                                                                                 int64
County Name                                                                               object
State_USA                                                                                 object
 Employment Status-Employed(Above 16 years)                                               object
Employment Status-Employed(Female)                                                        object
 Commuting to work with Public transport                                                  object
Working from home                                                                         object
 Occupation-Sales and office occupations                                                  object
 Industry-Educational services, and health care and social assistance                     object
Class of worker-Government workers                                                        object
Unpaid family workers                                                                     object
Income-Less than $10,000                                                                  object
Income-$200,000 or more                                                                   object
Median family income                                                                      object
With private health insurance                                                             object
No health insurance coverage                                                              object
With private health insurance(Employed noninstitutionalized population 19 to 64 years)    object
No health insurance coverage(Employed noninstitutionalized population 19 to 64 years)     object
18 to 64 years (People whose income in past 12 years is below poverty level)              object
65 years and over (People whose income in past 12 years is below poverty level)           object
dtype: object

In [106]:
Enrichment_covid_economic = pd.merge(super_covid_df,economic_df,on = ['countyFIPS','County Name'])
Enrichment_covid_economic

,countyFIPS,County Name,State,StateFIPS,2020-01-22_x,2020-01-23_x,2020-01-24_x,2020-01-25_x,2020-01-26_x,2020-01-27_x,...,Unpaid family workers,"Income-Less than $10,000","Income-$200,000 or more",Median family income,With private health insurance,No health insurance coverage,With private health insurance(Employed noninstitutionalized population 19 to 64 years),No health insurance coverage(Employed noninstitutionalized population 19 to 64 years),18 to 64 years (People whose income in past 12 years is below poverty level),65 years and over (People whose income in past 12 years is below poverty level)
0,1001,Autauga County,AL,1,0,0,0,0,0,0,...,21,1213,1022,72441,40853,4496,21383,2441,(X),(X)
1,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,131,4251,6183,82801,156322,21826,78564,12797,(X),(X)
2,1005,Barbour County,AL,1,0,0,0,0,0,0,...,23,1120,299,48768,11636,2313,6163,989,(X),(X)
3,1007,Bibb County,AL,1,0,0,0,0,0,0,...,0,528,234,67979,13148,2095,6435,973,(X),(X)
4,1009,Blount County,AL,1,0,0,0,0,0,0,...,73,1784,791,68945,38181,5854,19078,2540,(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3081,56037,Sweetwater County,WY,56,0,0,0,0,0,0,...,26,841,794,93852,31030,5594,15862,2782,(X),(X)
3082,56039,Teton County,WY,56,0,0,0,0,0,0,...,0,197,1641,113830,18728,2582,11622,1801,(X),(X)
3083,56041,Uinta County,WY,56,0,0,0,0,0,0,...,21,305,258,84504,14876,2288,7378,1347,(X),(X)
3084,56043,Washakie County,WY,56,0,0,0,0,0,0,...,10,100,89,71223,5540,812,2738,612,(X),(X)
3085,56045,Weston County,WY,56,0,0,0,0,0,0,...,7,215,99,71528,4461,846,2243,392,(X),(X)